lib/pages/popular/popular_page.dart
related issue https://github.com/Predidit/Kazumi/issues/40
=> fix: searchbar theme color

lib/app_widget.dart
=> fix linux tray: linux seems dont support setTooltip

lib/app_widget.dart
https://github.com/leanflutter/tray_manager/pull/43
=> fix tray icon not shown on linux flatpak or snap

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/other.yml
=> update issue template

lib/pages/player/player_item.dart
感谢您出色的工作。
希望在视频播放时能够支持更多的倍速播放选项。
=> feat: support more speed option

lib/main.dart, lib/modules/roads/road_module.dart, lib/pages/player/player_item.dart, lib/pages/video/video_controller.dart, lib/pages/video/video_page.dart, lib/plugins/plugins.dart, lib/utils/utils.dart
1.  除历史记录界面表现外，其他界面均修改为原始网页表现形式
2. 优化macOS启动时界面大小
=> 集数表现形式修改，macOS表现优化

lib/bean/appbar/sys_app_bar.dart, lib/bean/card/bangumi_history_card.dart, lib/pages/history/history_page.dart, lib/pages/menu/side_menu.dart, lib/pages/video/video_page.dart, pubspec.yaml
1. 修复小白条沉浸问题 #324
2. 针对 #255 的一个workaround，增加一个按钮用于快速定位到当前集数，为此增加了scrollview_observer依赖
3. 修改了一些间距，让界面看着更美观(我认为是更美观了，之前的都太靠近屏幕两侧了)
=> 修复小白条沉浸，增加一些padding

lib/pages/player/player_item.dart
1. #299 , #264 
2. 利用 KeyRepeatEvent, KeyUpEvent 和 timeStamp 实现长按时倍速播放，不需要定时器
3. 这个音量插件不能在电脑端调用系统音量调节面板，我没想到有什么更优雅的方案实现音量调节面板的延时关闭，还能保证连续多次按下时表现正常
=> keyboard enhancement

lib/pages/player/player_item.dart
=> mod: update danmaku duration to match play speed

lib/pages/player/player_item.dart
fd0a329 的效果是这样的：仅滑动也会显示音量条，volume_controller 也是如此且表现比 flutter_volume_controller 更差，至少 flutter_volume_controller 可以用延时解决这个问题，所以还是保留了这个依赖
https://github.com/user-attachments/assets/253349eb-a8b6-48e0-b671-10a20c8a0ba2
=> feat: better volume seeking behavior

lib/pages/player/player_item.dart
=> fix: back seeking loop

lib/utils/anime_season.dart
=> fix code logic bug

lib/bean/card/bangumi_info_card.dart, lib/utils/utils.dart
=> show info card airdate on phone devices

lib/bean/widget/scrollable_wrapper.dart, lib/pages/popular/popular_page.dart
原先电脑上只能使用横向滚轮滚动，
修改后支持纵向滚轮和左键拖动，
=> 优化桌面版推荐标签滚动

lib/bean/settings/settings.dart, lib/pages/player/player_item.dart
=> simplify code

lib/pages/player/player_item.dart
=> auto-fill anime title in danmaku search

lib/pages/player/player_item.dart
#502 
没能加速成功的右方向键长按将能快进10s。
使用`showPlaySpeed`变量做判断，总感觉很危险，但又感觉还好..
手势和右键如果同时使用，应该会有`lastPlayerSpeed`回不到原先的情况，但这是原本就存在的问题？
=> fix key-right up

lib/pages/popular/popular_controller.dart, lib/pages/popular/popular_controller.g.dart, lib/pages/popular/popular_page.dart
目前popular page中快速点击多个tag，页面会不断闪烁，我尝试解决了这一问题。
另外发现在page中有对`popularController.currentTag`进行赋值，我想尽量避免，不知这是否符合项目代码规范。
改这么多代码总感觉挺危险的，page中有什么需要额外考虑的吗。
另外点击多个tag时`searchLoading`的赋值看起来仍会有问题，我想尝试解决。
不知这pr是否需要所以我先提交draft pr了。
=> optimize popular page

.github/workflows/pr.yaml, .github/workflows/release.yaml
mac dmg中加个应用程序目录的软链接，直接拖过来安装进应用程序，更符合用户习惯，
=> Add Applications symlink to DMG installer

lib/pages/player/player_item.dart
Windows端ProgressBar拖动期间将不会自动隐去，
另外桌面端拖动进度条将暂停画面且更新右侧进度，和移动端效果一致。
另外发现移动端可以在ProgressBar不显示时就拖动进度，所以没改。
=> fix ProgressBar

lib/modules/plugin/plugin_http_module.dart, lib/pages/plugin_editor/plugin_shop_page.dart, lib/pages/plugin_editor/plugin_view_page.dart, lib/plugins/plugin_install_time_tracker.dart, lib/plugins/plugin_validity_tracker.dart, lib/plugins/plugins.dart, lib/plugins/plugins_controller.dart, lib/request/query_manager.dart
优化规则管理， 
1. 规则仓库页添加规则更新时间显示和排序，
1. 规则管理页添加规则安装时间显示和排序，
1. 规则管理页添加多选删除功能，长按item触发，
1. 内存记录有搜索成功过的插件，在规则管理页显示“搜索有效”，
全部合起来总之就是方便批量卸载没用的规则，
=> Optimize plugin management features

lib/pages/plugin_editor/plugin_view_page.dart
@AoEiuV020 @xxfttkx 因为修改了你们的代码，所以想要征求你们的意见
修改 ListTile 的 shape 让他匹配 Card，以及修改 `可更新` 的表现形式，让他更突出
=> modify plugin view page

lib/pages/player/player_item.dart
修改了`onDragStart`没有停止`playerTimer`的问题。
另外发现就算是点击进度条也会进行`onDragStart`和`onDragEnd`，就把`playerTimer = getPlayerTimer();`放`onDragEnd`中了，以和`onDragStart`对应。
=> fix ProgressBar bug

lib/pages/popular/popular_controller.dart, lib/pages/popular/popular_page.dart
解决了“搜索过后再退出搜索时searchKeyword没reset，会导致点击card时使用searchKeyword”的问题
=> fix search bug

lib/bean/dialog/dialog_helper.dart
=> Revert "fix snackbar bug"

lib/pages/timeline/timeline_page.dart
空的Container会引起一些UI的显示不同，找不到原因，就直接删了
改动前↑    改动后↓
=> delete empty Container

lib/pages/timeline/timeline_controller.dart, lib/pages/timeline/timeline_page.dart, lib/utils/utils.dart
修改了第一次点开时间机器时的显示问题
改动前↑    改动后↓
=> fix timeline

lib/pages/popular/popular_controller.dart
=> optimize search

lib/bean/card/bangumi_history_card.dart, lib/bean/widget/collect_button.dart
改了点代码，但不知道是否必要，希望得到你的建议
首先是break，逻辑是更清晰了，但考虑到plugin列表的长度，又会想其实加不加都无所谓。
还有，collect_button中，把const的多个PopupMenuItem整合到for循环中了，代码量减少了，但感觉是不会会导致代码难以阅读。
另外，看到有tooltip的字段却赋的是空值，似乎是为了取消tooltip的显示。我加上了对应的collectType值，以防看到不知道图标代表什么时需要点开。但这应该是设计方面的问题，有必要显示tooltip吗，之前选择不显示的考量是什么呢。
=> optimize code

lib/bean/card/bangumi_history_card.dart, lib/pages/player/player_controller.dart, lib/pages/player/player_item.dart, lib/utils/utils.dart
=> enhance pc play

lib/plugins/plugins_controller.dart
=> fix plugin remove bug

lib/bean/widget/collect_button.dart, lib/pages/player/player_item.dart, lib/pages/player/player_item_panel.dart, lib/pages/player/smallest_player_item_panel.dart, lib/pages/video/video_page.dart
`consumeOutsideTap: true` 可以解决出界和点击外部关闭导致暂停/播放视频的问题，表现为面板隐藏时 menu 不会移动
=> fix player panel

lib/bean/card/bangumi_card.dart, lib/bean/card/bangumi_info_card.dart
昨天提到了 hero 就去看了眼，感觉非常适合进入 info_page 时海报图的切换，于是就改了
唯一的问题是如果图片被隐藏了部分它的表现就不是特别好
https://github.com/user-attachments/assets/a1e6093d-c3a0-48d9-8514-8d99a16dc2f2
=> hero transition for bangumi image

README.md
我是Arch Linux用户，比较喜欢Kazumi，但之前发现Kazumi没有针对Arch的安装方式。
使用Flathub商店虽然也可安装，但会同时安装GNOME组件，对于Arch使用KDE等桌面的用户来说并不方便，且使用Flathub安装程序对部分Arch用户来说也不合适。
我目前维护着Kazumi的AUR软件包：https://aur.archlinux.org/packages/kazumi
它是基于本仓库Releases发布的tar.gz进行二次打包构建为Arch Pacman软件包的实现，PKGBUILD源码可在[Kazumi AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kazumi)相关页面查看，仓库完全开源，过程无二次植入等行为。
希望能够添加针对Arch AUR的安装方式。
附使用yay安装Kazumi的完整过程：
```bash
❯ yay kazumi
2 aur/kazumi-bin 1.4.0-1 (+1 0.12) (过时的: 2024-12-10) 
基于自定义规则的番剧采集APP，支持流媒体在线观看，支持弹幕。
1 aur/kazumi 1.5.3-1 (+0 0.00) 
基于自定义规则的番剧采集APP，支持流媒体在线观看，支持弹幕。
==> 要安装的包 (示例: 1 2 3, 1-3 或 ^4)
==> 1
AUR Explicit (1): kazumi-1.5.3-1
:: (1/1) 下载了 PKGBUILD: kazumi
1 kazumi                           (构建文件已存在)
==> 清理哪些软件包的构建文件？
==> [N]没有 [A]全部 [Ab]中止 [I]已安装 [No]未安装 或 (1 2 3, 1-3, …
```
=> feat: Add Arch Linux installation method

.github/workflows/pr.yaml
https://stackoverflow.com/questions/49934684/sed-i-on-freebsd/49934903#49934903
=> fix sed in ci runs on macos

lib/pages/player/episode_comments_sheet.dart, lib/pages/video/video_page.dart
新年快乐！
两个修复
- 桌面全屏时的选集菜单宽度是屏幕高度，特别宽
- 因为懒加载导致的评论区滚动问题的复现
=> another fix for player

README.md
=> add fdroid to readme

lib/bean/widget/error_widget.dart, lib/pages/about/about_page.dart, lib/pages/error/storage_error_page.dart, lib/pages/info/info_page.dart, lib/pages/plugin_editor/plugin_shop_page.dart, lib/pages/popular/popular_page.dart
Dialog 套 Dialog，感觉非常丑陋，但是感觉有必要允许保存并删除
https://github.com/user-attachments/assets/e0a58062-fd89-4652-a481-d1fd3616ad32
=> feat: support multiple actions in error widget

lib/bean/card/bangumi_card.dart, lib/pages/info/info_page.dart, lib/pages/popular/popular_controller.dart
=> refactor: remove useless `popularController.keyword`

lib/pages/index_module.dart
=> feat: Material You like tab transition

lib/pages/popular/popular_page.dart
=> Feat  #787  优化主页搜索框表现

lib/bean/card/bangumi_info_card.dart, lib/pages/info/info_page.dart, lib/pages/info/info_tabview.dart, pubspec.lock, pubspec.yaml
fix #853 
https://github.com/user-attachments/assets/79c2b6d7-342b-4d59-928b-d9af3be66072
=> fix: info page appearance

lib/bean/card/character_card.dart, lib/bean/card/staff_card.dart
=> feat: add info only pic when avatar is empty

lib/bean/card/bangumi_card.dart, lib/bean/card/bangumi_history_card.dart, lib/bean/card/bangumi_info_card.dart, lib/utils/constants.dart
把图片圆角改成和 Card 一样的 12
然后删了点多余的 ClipRRect，NetworkImgLayer 已经裁剪过了，不用再裁剪一次(就是不知道这有没有性能提升，感觉原来的代码也可能被优化性能)
=> chore: change imgRadius to Card default radius

README.md
Kazumi is available on archlinuxcn: https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/kazumi
=> docs(README): add aur/kazumi-bin & archlinuxcn/kazumi

lib/pages/settings/danmaku/danmaku_settings_sheet.dart
=> fix: 弹幕字号为 31 时出现多余小数位

macos/Runner.xcodeproj/project.pbxproj, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, macos/Runner/Base.lproj/MainMenu.xib, macos/Runner/en-GB.lproj/MainMenu.strings, macos/Runner/en.lproj/MainMenu.strings, macos/Runner/zh-Hans.lproj/MainMenu.strings
#1125 
设置默认语言为简体中文，生成了默认英文的菜单栏语言文件 (没啥用，但是如果后面要做软件内英语翻译就有用了)
应用名首字母大写
=> feat: add macOS menuBar l10n support

lib/pages/player/player_controller.dart, lib/pages/player/player_item_panel.dart, lib/pages/settings/player_settings.dart, lib/utils/constants.dart, lib/utils/storage.dart
=> 添加全局裁切方式设置

lib/pages/webview/webview_controller_impel/webview_android_controller_impel.dart, lib/pages/webview/webview_controller_impel/webview_apple_controller_impel.dart, lib/pages/webview/webview_item_impel/webview_android_item_impel.dart, lib/pages/webview/webview_item_impel/webview_apple_item_impel.dart
=> refactor: better webview log for Android and Apple platforms

lib/pages/player/player_item.dart, lib/pages/webdav_editor/webdav_editor_page.dart, lib/utils/storage.dart, lib/utils/webdav.dart
=> Revert "feat: Improve WebDAV sync"

lib/pages/collect/collect_controller.dart, lib/pages/player/player_item.dart, lib/utils/webdav.dart
修复了 collectchanges sync 文件名不同的bug
稍微整理了一下 update 和 download 方法
=> fix collectchanges sync

lib/pages/player/player_item.dart, lib/pages/player/player_item_panel.dart, lib/pages/player/smallest_player_item_panel.dart, lib/pages/settings/super_resolution_settings.dart, lib/utils/storage.dart
用于关闭 #1302 
重新优化了一下 已经在Win/iOS上测试 应该没有什么问题
=> feat(ui): handleSuperResolutionChange
