Predidit/Kazumi

- android/app/src/main/kotlin/com/example/kazumi/MainActivity.kt
- ios/Runner/AppDelegate.swift
- lib/pages/player/player_controller.dart
- lib/pages/player/player_item.dart
- lib/pages/webview_desktop/webview_desktop_controller.dart
- lib/utils/remote.dart
- pubspec.lock
- pubspec.yaml
相关issue #74 #23 
#74 说明
- 投屏通过 UPnP(DLNA) 技术实现，在不支持此技术的设备上，投屏功能不会生效
- 建议说明 UPnP(DLNA) 投屏要求为在同一网络下
- 建议说明 Windows 10 及更早的版本中，Windows Media Player 对 m3u8 的播放支持不完整，这不是投屏功能的 Bug
- 尚不明确是否需要制作额外的 DLNA 投屏控制页面。经测试，投屏到 Android 电视上的内容可以通过遥控器直接操作，故暂不实现
#23 说明
- 在 Android / iOS 设备上，外部播放的实现方式为打开指定 MIME 类型为 `video/mp4` 的链接
- iOS 设备需要进行测试（手头没设备），我已将 iOS 相关代码注释，**详见 PR 文件中 `ios/Runner/AppDelegate.swift` 和 `lib/utils/remote.dart` 中的注释部分**
- Windows 平台目前仅支持浏览器打开，**原因详见 PR 文件中 `lib/utils/remote.dart` 中的注释部分**。需要更好的实现办法
> New features: DLNA video cast & External video player support

- lib/utils/utils.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
相关 issue #32 
当 `Utils.getScreenInfo()` 获取到系统屏幕信息时，返回一个类型为 `Future<Map<String, double>>` 的值；
该值包含屏幕宽度 `width` 、屏幕高度 `height` 和缩放比例 `ratio` 。
当获取失败时，返回 `null` 。
剩下的就是适配了（没做）
> update function Utils.getScreenInfo()

- lib/utils/utils.dart
弃用 `MediaQuery.of(context).devicePixelRatio;`
用 `MediaQueryData.fromView().devicePixelRatio;` 代替
> deprecate BuildContext in Utils.getScreenInfo()

- .github/workflows/pr.yaml
- .github/workflows/release.yaml
> correct owner and group can be useful for rootless builds

- lib/bean/appbar/sys_app_bar.dart
- lib/pages/player/player_item.dart
- lib/utils/utils.dart
修正前，超过1h的视频时长无法正确显示，如图：
修正后显示效果如下：
应用退出按钮可见界面右上角。
> Fix time display issue on video player

- lib/pages/player/player_item.dart
- lib/utils/remote.dart
1. 增加外部播放时自动暂停和播放源检测
2. 修复#303 
3. 修复macOS和iOS在触发外部播放对话框后，点击框外关闭会导致无法再次拉起对话框，现在无法通过点击框外关闭
> 增加自动暂停和播放源检测；修复macOS和iOS的bug

- lib/pages/about/about_page.dart
fix #297
通过删除缓存目录的方式实现清除缓存的方式
CachedNetworkImage version 2.3 版本之后原本的 `emptyCache` 失效
只能通过 CachedNetworkImage 自带的 `.evictFromCache(url)` 去实现，不过当前项目要是需要记录所有的 url 改动有点大，折中方案的话，可以直接删除整个缓存目录
> fix:  #297 清除缓存功能失效

- lib/bean/card/bangumi_history_card.dart
- lib/modules/history/history_module.dart
- lib/modules/history/history_module.g.dart
- lib/pages/history/history_controller.dart
- lib/pages/player/player_item.dart
- macos/Runner/Info.plist
1. 新旧版本hive结构互相兼容，新版本在旧版本上显示第几话，旧版本在新版本上显示相同，点开播放后恢复原始网页表现形式。
2. 增加允许macOS播放http视频源设置，iOS已经允许不需要做改动
> Add episodeName to hive to display it in history card

- lib/bean/appbar/sys_app_bar.dart
- lib/pages/popular/popular_page.dart
fix #325 
<p float='left'>
</p>
找个一个解决办法了，现在由于 ` const SizedBox(width: 10,)` 导致 **A RenderFlex overflowed by 10.0 pixels on the right**，新增一个 leadingWidth 的属性，然后让默认的 leadingWidth 宽度增加 10 就好了，默认是 56，所以这里的宽度设置为 66 ，就可以解决问题了
> fix: A RenderFlex overflowed by 10.0 pixels on the right

- lib/utils/remote.dart
fix #320 
灵光乍现
之前就猜想到是否是dlna未被正常释放。不如说最困扰我的问题是我不知道怎么添加onDismissCallback方法
> fix dlna searcher is not correctly stoped on macOS and iOS when dialog is dismissed by clicking on the mask

- lib/bean/card/bangumi_card.dart
- lib/pages/plugin_editor/plugin_view_page.dart
- lib/pages/popular/popular_page.dart
- lib/pages/timeline/timeline_page.dart
- macos/Runner/AppDelegate.swift
1. 给macOS增加了外部播放的软件选择。
至于iOS平台，我认为手机端的外部播放主要作用在于DLNA，因此不考虑为此花时间增加功能。
2. 依然是一些间距的修改，现在bangumi card可以显示2/3行标题了
> Add macOS external player selector

- lib/pages/player/player_item.dart
- lib/pages/video/video_controller.dart
- lib/pages/video/video_page.dart
- pubspec.yaml
https://github.com/user-attachments/assets/699e05e4-64eb-42bb-84cd-03fe405e8819
> feat: 不需要按钮的定位集数功能，全屏现在也可以选集了

- lib/pages/history/history_page.dart
- lib/pages/player/player_item.dart
- lib/utils/constans.dart
fix #226 
顺便修改了一个手机平台历史记录 clear_all 按钮会挡住 delete 按钮的 UI 问题
> fix iOS above 2.0 playback speed bug

- lib/pages/player/player_item.dart
- lib/pages/settings/player_settings.dart
- lib/utils/constans.dart
- lib/utils/storage.dart
支持拓展倍速选项，启用后可以选择可能不支持的 2.0 以上的倍速选项。
> feat: add extend play speed

- lib/bean/appbar/sys_app_bar.dart
- lib/pages/menu/side_menu.dart
- lib/pages/popular/popular_page.dart
1. #362 , #341 
2. `centerTitle: true` 是因为 macOS 不这样设置有的页面标题在左边有的页面标题在中间，Windows 就只会出现在左边。macOS 总有些奇奇怪怪的 bug
> press logo jump to history page

- ios/Runner/AppDelegate.swift
- ios/Runner/Info.plist
- lib/pages/player/player_item.dart
- lib/utils/remote.dart
- macos/Runner/AppDelegate.swift
macOS 的 VLC 以及 macOS/iOS 的 AVPlayer 都可以支持 referer 请求头
> add macOS/iOS external player referer support

- lib/bean/card/episode_comments_card.dart
- lib/pages/info/comments_sheet.dart
- lib/pages/logs/logs_page.dart
- lib/pages/player/episode_comments_sheet.dart
- lib/utils/utils.dart
- pubspec.yaml
两个已知问题
1. fontSize 好像不生效
2. 滑动有的时候会跳跃一下，我没找到解决办法
> add rich text parser, make comments and logs selectable

- lib/pages/player/player_item.dart
#390 
`iOS: needs to update MPVolumeView visibility, otherwise pressing physical buttons won't display volume slider after [showSystemUI] is reset to true.`
> fix(ios): volume controll

- lib/pages/info/info_controller.g.dart
- lib/pages/player/player_item.dart
- lib/pages/settings/player_settings.dart
- lib/pages/video/video_controller.dart
- lib/pages/video/video_controller.g.dart
- lib/pages/video/video_page.dart
- lib/pages/webview/webview_controller_impel/webview_apple_controller_impel.dart
- lib/pages/webview/webview_controller_impel/webview_controller_impel.dart
- lib/pages/webview/webview_item_impel/webview_windows_item_impel.dart
- lib/utils/constants.dart
1. Closes #449 
2. 主要修改就是只用 Focus 包裹 playerSurface，同时增加 ruturn KeyEventResult.handled
3. 把 androidFullscreen 重命名为 isFullscreen (才发现之前修改 info_controller.dart 没执行过 `dart run build_runner build`)
4. 恢复 iOS 平台 2.0 以上播放倍速的选项
> miscellaneous improvments

- macos/Runner/AppDelegate.swift
根据 macOS 编译器提示做的修改
```
macos/Runner/AppDelegate.swift has been modified and cannot be automatically migrated.
We recommend developers override applicationSupportsSecureRestorableState in AppDelegate.swift as follows:
override func applicationSupportsSecureRestorableState(_ app: NSApplication) -> Bool {
return true
}
```
> make macOS builder happy

- lib/pages/menu/menu.dart
- lib/pages/menu/side_menu.dart
简化路由代码，另外能问一下使用手动`notifyListeners();`代替`setState`的原因吗
> simplify code

- lib/pages/collect/collect_page.dart
对追番列表排序
避免多次重复遍历collectedBangumiList
> mod: sort collected bangumi

- lib/pages/init_page.dart
> optimize loop logic

- README.md
- lib/bean/card/bangumi_info_card.dart
- lib/modules/bangumi/bangumi_item.dart
- lib/modules/bangumi/bangumi_item.g.dart
- lib/modules/bangumi/bangumi_tag.dart
- lib/modules/bangumi/bangumi_tag.g.dart
- lib/modules/characters/character_item.dart
- lib/modules/history/history_module.dart
- lib/modules/history/history_module.g.dart
- lib/pages/collect/collect_controller.dart
- lib/pages/info/comments_sheet.dart
- lib/pages/info/info_controller.dart
- lib/pages/info/info_page.dart
- lib/pages/player/player_item.dart
- lib/pages/settings/danmaku/danmaku_settings.dart
- lib/pages/settings/player_settings.dart
- lib/pages/settings/theme_settings_page.dart
- lib/pages/video/video_page.dart
- lib/request/bangumi.dart
- lib/utils/storage.dart
- lib/utils/utils.dart
修改：
- bangumiItem 增加 tags，通过设置 HiveField defaultValue 保持兼容，否则会出现已存在另一个实例，打开失败的错误
- info_page summary 修改到 fab 的详情中，增加 tags
- info_page 在打开时进行一次 Api 更新，更新 rank、tag 和 summary
- 将原来打开视频源的按钮放到 sysAppBar 里面
- 修改了电脑端 wrap 的 runSpace，让间距看起来更好看
一些疑问：
- 退出 info_page 后更新的 bangumiItem 没有被保存，不清楚怎么让他保存
- Collect 好像增加了 webdav 同步，但是没有在设置里面增加同步选项，没法开启。
> modify info page

- lib/pages/settings/danmaku/danmaku_settings_window.dart
- lib/utils/constants.dart
电脑上弹幕上限太小了， 既然默认大小是1.5倍，那么最大值也给个1.5倍吧，这里把电脑版最大值从32改成了48，
其实最好是能不使用“字号”而是“百分比”来设置弹幕大小，想B站一样， 甚至能实现切全屏时弹幕跟着放大，这样更舒服，但是实现有点麻烦，需要设计算法还不好兼容旧版就没做，只改个最大值凑合一下，
> increase maximum font size for non-compact devices

- lib/pages/popular/popular_controller.dart
- lib/pages/popular/popular_page.dart
问题在于方法使用错误，新刷新到的番剧显示在了当前番剧下面而不是覆盖当前番剧。
由于`RefreshIndicator`获取不到`filter`所以又新增了个`queryBangumiListFeedByRefresh`方法。
有个问题，
```
Future<bool> queryBangumiListFeedByRefresh() async{
return await queryBangumiListFeedByTag(currentTag);
}
```
与
```
Future<bool> queryBangumiListFeedByRefresh(){
return queryBangumiListFeedByTag(currentTag);
}
```
在这种情况下似乎作用是相同的，在目前没有try catch的需求下，是使用上面方法，与别的`queryBangumi`方法达成格式一致好；还是使用下面的，力求代码简洁呢。
> fix refresh bug

- .gitignore
- lib/bean/card/comments_card.dart
原 PR 为增加 macOS 红绿灯
修改为 comments card 相关
> modify comments card

- lib/bean/card/network_img_layer.dart
- lib/bean/settings/color_type.dart
- lib/pages/info/info_page.dart
- lib/pages/settings/theme_settings_page.dart
- 增加背景虚化，我给的 15，可改
- 启用主题颜色指示器，加了个 Material Design 3 的默认颜色。(另外目前的颜色里面有几个几乎没什么区别，或许可以考虑减掉几个，参考 [ColorScheme.fromSeed constructor](https://api.flutter.dev/flutter/material/ColorScheme/ColorScheme.fromSeed.html#material.ColorScheme.ColorScheme.fromSeed.1) Line 436-453)
> theme improvments

- .github/workflows/pr.yaml
理论上的效果：
- draft 不会触发 workflow
- 如果只修改了平台文件则只会运行对应平台的 job
- 可以手动添加任意平台的 job
- 修改非平台文件会全部运行
> Mod pr workflow

- lib/bean/dialog/dialog_helper.dart
当有snackbar时进行didPush时会报这种错，虽然好像不影响使用，
另外发现好多page例如history_page在build时先进行了一行`WidgetsBinding.instance.addPostFrameCallback((_) {});`，这是什么原因，我注释掉后页面也能正常打开
> fix snackbar bug

- lib/pages/timeline/timeline_controller.dart
- lib/pages/timeline/timeline_page.dart
- lib/utils/utils.dart
时间机器这边代码太乱了，就整理了下。
有个问题，目前点击时间机器中按钮时，有判断是不是当前季度，并执行不同获取操作。
我认为可以简化如下代码
```
if (AnimeSeason(
timelineController
.selectedDate)
.toString() ==
AnimeSeason(DateTime.now())
.toString()) {
await timelineController
.getSchedules();
} else {
await timelineController
.getSchedulesBySeason();
}
```
变成这样
```
await timelineController .getSchedulesBySeason();
```
发现获取到的动画有区别，能简化吗
> simplify time code

- .github/workflows/pr.yaml
- .github/workflows/release.yaml
Use `cp -a` instead of `cp -r` to preserve symlinks when copying the macOS app bundle. This prevents symlinks from being converted to regular files, which would unnecessarily increase the final DMG size.
https://github.com/Predidit/Kazumi/pull/517
> fix(ci): preserve symlinks when copying macOS app bundle

- lib/pages/popular/popular_page.dart
https://github.com/Predidit/Kazumi/issues/338 相关
解决了搜索框在切换页面时的保留。
有个问题。查了一下，`TextFormField`适合复杂的表单处理，搜索框更适合`TextField`。就把`TextFormField`换成`TextField`了，发现也能正常工作，当时为什么选择了`TextFormField`？
> optimize search

- lib/bean/card/bangumi_history_card.dart
- lib/bean/widget/collect_button.dart
> Mod history card

- lib/pages/player/episode_comments_sheet.dart
- lib/pages/player/player_item.dart
- lib/pages/video/video_page.dart
修复上一个 PR 的 Timer 问题
移动评论区，和选集放在一起。这样做的好处是比较整齐，后续有 bangumi 登录之后也可以增加发送评论的功能，会比较好看
- maintain state 和 keep alive 是为了避免反复构建评论区造成的卡顿
- 手机端全屏只会呼出选集，不会呼出评论区
> mod: move episode comments to menu

- lib/pages/player/episode_comments_sheet.dart
- lib/pages/player/player_item.dart
- lib/pages/video/video_page.dart
不保存状态了，用 Sliver 的懒加载解决卡顿问题
另外现在的播放器有两个问题
- 手机端切换全屏会导致 player_item_panel 消失
- 控制台报异常(这个把 player_item_panel 的 build 里最顶层的 Expanded 删了可以解决)
```shell
======== Exception caught by widgets library =======================================================
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.
The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type StackParentData.
Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Stack widget.
The ownership chain for the RenderObject …
```
> fix comments bug when changing episode

- lib/bean/card/bangumi_card.dart
- lib/pages/popular/popular_controller.dart
- lib/pages/popular/popular_page.dart
#579 相关，
仍有问题：
点击搜索栏右边的×后，
即通过searchKeyword进入info变成了通过bangumi.name。这是正常的表现吗，看了一下，之前的代码应该也有这种问题。
> fix search

- lib/pages/player/player_controller.dart
- lib/pages/player/player_item.dart
优化音量控制代码。
问个问题，有的番剧就算音量拉满也感觉还是太小声。我尝试把volume的最大值改成200，即在setVolume中`value = value.clamp(0.0, 200.0);`，发现是能正常工作的，似乎mpv支持这种设置。项目是否考虑这个功能。
> optimize volume code

- lib/pages/init_page.dart
- lib/pages/plugin_editor/plugin_editor_page.dart
- lib/pages/plugin_editor/plugin_view_page.dart
- lib/plugins/plugins_controller.dart
#143 相关。
添加规则拖拽排序，可自由拖拽排序并应用在info_page中。重写了规则保存逻辑。
@AoEiuV020  和sortByName有一定重复所以删掉了，如果需要时间相关信息的话可以在updatePlugin中写，我感觉没必要就没写。
> add plugin drag feature

- lib/plugins/plugins_controller.dart
> fix plugin save

- lib/pages/player/player_controller.dart
> fix #590 (Volume persistence)

- lib/bean/card/bangumi_info_card.dart
- lib/pages/collect/collect_page.dart
之前 collect button 手机上有个小 bug 一直没发现，背景会比 icon 大一圈，这是手机平台独有的问题
> fix collect button size

- lib/pages/player/player_item.dart
> fix #598(pause before hide player)

- lib/app_widget.dart
- lib/pages/init_page.dart
不知道是不是个例，我的手机上如果开启动态配色会一直是浅色模式
看上去像是 dynamic_color 包获取的问题，但逻辑怎么看都没什么问题
> fix android dynamic theme is always in light mode

- android/app/build.gradle
- pubspec.yaml
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/18472#note_2300963696
本地测试编译后的文件是正确的 1522
传上来看看 GHA 的正不正常
> meet f-droid version code requirement

- lib/bean/widget/collect_button.dart
- lib/pages/info/info_page.dart
- lib/pages/player/player_item.dart
- lib/pages/player/player_item_panel.dart
- lib/pages/player/smallest_player_item_panel.dart
- lib/pages/video/video_page.dart
要修改的东西非常多，目前只改了 PC 端的界面，先传上来 review 一下，多平台的适配后面再慢慢改，有可能需要复制一份 player_item_panel.dart 单独展示手机端的界面
PopUpMenuButton 官方文档推荐改为使用 MenuAnchor，我试了一下 hover 的 highlight 看着好看了很多，于是我全部改了（
https://github.com/user-attachments/assets/492aaafa-fecf-490d-956c-b1aa6fc1ba25
https://github.com/user-attachments/assets/09dfa57e-20fd-45c2-a59e-892e95f3eacf
> refactor pc player panel

- lib/bean/widget/collect_button.dart
- lib/pages/player/player_controller.dart
- lib/pages/player/player_controller.g.dart
- lib/pages/player/player_item.dart
- lib/pages/player/player_item_panel.dart
- lib/pages/player/smallest_player_item_panel.dart
- lib/pages/video/video_page.dart
- pubspec.lock
- pubspec.yaml
Xcode 升级完罢工了，CocoaPod broken。
电脑端因为升级前就一直开着软件所以 hot reload 可以调试，手机端直接调不了了
最令我无语的是不知道为什么安卓也调试失败了 :(
电脑端应该没啥问题，鼠标进入 player panel 后不会隐藏，打开 MenuAnchor 禁止隐藏，关闭时恢复
> optimize panel hide logic

- lib/bean/card/network_img_layer.dart
- lib/pages/player/player_item.dart
- lib/pages/player/player_item_panel.dart
- lib/pages/video/video_page.dart
- lib/request/bangumi.dart
- pubspec.lock
- pubspec.yaml
为了防止 F-Droid 又出什么意外或许可以在主仓库增加一个开发 branch，然后 PR merge 到开发 branch里，在更新版本时进行 cherry-pick / merge 到 main。虽说 gitlab CI 已经通过了，应该不会有什么意外了。
因为并没有发布 pre-release 和 cherry-pick 新功能之类的问题，专门的开发 branch 倒也是可有可无。
> fix player panel

- lib/pages/player/player_item.dart
- lib/pages/player/player_item_panel.dart
- lib/pages/player/smallest_player_item_panel.dart
B 站也是抬高底部面板的做法。
但是阴影不好修改，就降低了渐变的起始颜色透明度，增大高度
> fix player panel with system navigation bar

- lib/pages/player/episode_comments_sheet.dart
还是不能用 AutomaticKeepAliveClientMixin 。吃一堑吃一堑（
手机端切集后会自动获取评论并加载一页，而不是 tab 切过去才获取
它在 ohos 上的表现和安卓，iOS 上的表现也会不一样，切集完全不会重新加载，应该有其他地方的原因
> remove keepAlive in comments sheet

- lib/bean/card/bangumi_card.dart
- lib/bean/card/bangumi_history_card.dart
- lib/pages/about/about_page.dart
- lib/pages/history/history_page.dart
- lib/utils/utils.dart
> Fix #683 (bangumi cards text overflow)

- lib/bean/appbar/sys_app_bar.dart
- lib/bean/widget/embedded_native_control_area.dart
- lib/pages/settings/decoder_settings.dart
- lib/pages/settings/super_resolution_settings.dart
没注意手机端的问题，safearea 会导致滚动区域的 statusbar 的颜色和 appbar 不一致，ohos 的 statusbar 上的 icon 颜色会出错
macOS 的差色问题解决不了，唯一的办法是 `forceMaterialTransparency: true,` 也就是滚动区域滑动到 appbar 底下时不变色，但是这不符合 material 3 规范
> fix status bar

- lib/pages/player/player_item.dart
- lib/pages/player/player_item_panel.dart
PR 的起因是 ohos 的小窗横屏需要用最小面板，所以用 size 代替判断
应该没啥问题，600 是 material 3 的 compact layout breakpoint
把 Text 放 DragToMoveArea 里解决选集名称太长导致的溢出问题和无法拖动窗口的问题
> chore: use size to decide which panel is used

- lib/pages/player/player_item.dart
- lib/pages/player/player_item_panel.dart
- lib/pages/player/smallest_player_item_panel.dart
场景：弹幕匹配错误，第七集匹配的第六集弹幕，但是手动搜索到第七集却没有弹幕，此时还是在正常播放第六集弹幕但是无法关闭
话说为什么有两个 danmakuController，一个 danmakuController 和一个 playerController.danmakuController
> fix(danmaku): cannot close danmaku if danmaku become empty after search

- lib/pages/player/player_item.dart
- lib/pages/player/player_item_panel.dart
- lib/pages/video/video_page.dart
- lib/utils/constants.dart
测试地狱
* 只要窗口宽度大于高度就用侧边菜单，不考虑 breakpoint
* gridDelegate 用 mainAxisExtent 解决电脑上调节窗口大小时高度不断变化导致定位集数位置错误
* 用 Flexible 解决手机端横屏点击弹幕输入框呼出的键盘会挡住输入框的问题
其他的基本都写在注释里了
> feat(ui): adaptive layout for video page

- lib/app_widget.dart
- lib/pages/init_page.dart
- lib/pages/video/video_controller.dart
Modular.setObservers([KazumiDialog.observer]); 貌似会报错，和之前动态取色类似的错误。
```
setState() or markNeedsBuild() called during build.
This ScaffoldMessenger widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
ScaffoldMessenger
The widget which was currently being built when the offending call was made was:
Builder
```
> fix: fix exceptions thrown from windowManager

- lib/bean/card/bangumi_card.dart
按我的理解，PopularController.keyword是用来检索视频源的关键词，在每次点进番剧卡片时被赋值为番剧名字。但是原本这儿做了个判断，如果是在搜索结果中就直接使用搜索时的关键词。
我把这个判断去掉了，因为他会造成几个问题：
1.每个搜索结果点开，下面的视频源都是一样的
2.在搜索中点开该番剧，与在追番中点开该番剧看到的视频源不同
3.番剧名与下面的视频不匹配
举个例子，搜索“摇曳百合”，下面也会出现“摇曳露营Δ”，点开“摇曳露营Δ”，下面出现的还是摇曳百合相关的视频源
1.5.8 release:
修复后：
> fix keyword when searching

- lib/pages/player/player_item_panel.dart
Fix: Toolbar edge obscured by screen in landscape mode
before:
after:
> fix: toolbar edge obscured by screen in landscape mode

- lib/pages/popular/popular_controller.dart
依据https://github.com/Predidit/Kazumi/issues/53#issuecomment-2665352386 进行修改，
得益于https://github.com/Predidit/Kazumi/pull/742 ，可以直接修改输入框部分的代码而不会影响源的搜索内容。
添加可以直接在搜索框中根据bangumi_ID搜索的功能，用来解决部分新番由于打分人数过少被筛选掉的问题。
同时纯数字搜索才会触发，不会影响到针对于正常内容的搜索。
经过测试，正常通过ID进行搜索：
对于其他内容的搜索仍然正常，未破坏原有功能：
对于返回的单个结果或是多个结果都保持了原有功能：
> feat: support searching by bangumi_id

- lib/pages/player/episode_comments_sheet.dart
- lib/pages/video/video_page.dart
本来准备直接用 CircularProgressIndicator()，但是不知道为什么把这段代码放 `didChangeDependencies` 里面会导致重复请求多次评论；RefreshIndicator 只会请求一次，也不是 `addPostFrameCallback` 的原因
```dart
if (infoController.episodeCommentsList.isEmpty) {
setState(() {
isLoading = true;
});
loadComments(widget.episode);
}
```
> fix: episode comments sheet missing animation

- lib/bbcode/bbcode_widget.dart
Mujica 第二集评论区，如果遮罩底下是超链接会无视遮罩直接跳转网页
这个修复太小了，我有考虑过直接开个 issue 等攒多一点 bbcode 相关的问题再一起修复，想想算了，应该碰不到那么多问题（
> fix(bbcode): link can be triggered when masked

- lib/pages/player/player_controller.dart
close #732 
应该和 `value / 100` 的精度有关，setVolume 的用处在桌面端，所以让移动端不在初始化的时候设置音量解决这个问题，移动端一直用的系统音量，不手动设置也没啥关系。
可惜 ohos 只允许调节播放器音量不能调节系统音量，永远无法与其他平台同步了
> fix(volume): mute when volume is too low

- lib/pages/popular/popular_controller.dart
- lib/pages/popular/popular_controller.g.dart
- lib/pages/popular/popular_page.dart
- lib/request/bangumi.dart
popular page 有三个刷新指示，删到只有一个 LinearProgressIndicator 了。
1. 增加了一个 trendList，因为现在的 trend 不会经常变化，所以缓存减少请求次数(减不了多少感觉)
2. 同样的原因，把下拉刷新删了
3. 改了点函数名字和返回值，改函数名是因为我不理解原来的函数含义是什么，大致理解了一下，可能改的不是很对。返回值因为我看完全没用到就删了改成空返回了
4. 现在一次性请求 24 个 bangumiItem，这样手机和电脑端最后一行都会被占满，加载更无感？
> refactor: query logic in popular page

- lib/bean/card/character_comments_card.dart
- lib/bean/card/episode_comments_card.dart
- lib/pages/player/player_item_panel.dart
- lib/pages/player/smallest_player_item_panel.dart
颜色替换是缺少 `#`，反而桌面端可以正常工作比较不正常。
有 replies 的 card 会有奇怪的表现，不知道安卓是不是也会这样。剧集评论区只有 ohos 会出现，但是角色评论卡在 iOS 上也出现了相同的问题，所以就统一加上了 9d07682ae6948a62c02c56898fdf2ba12890dae3
> fix(ui): comments and svg appearance

- lib/bbcode/bbcode_widget.dart
* 修复没有遮罩的链接无法正确跳转
* 优化鼠标悬浮表现
* 增加超链接下划线
* 统一文本选择高亮的高度
mask 的问题与这个有关，而且还没有圆角。暂时没找到更好的表现方式，如果用 WidgetSpan + Stack 叠加无法正确的换行。
https://github.com/flutter/flutter/issues/144753
目前和 Bangumi 的做法类似，但是没办法实现这样的效果
```html
<span class="text_mask" style="background-color:#555;color:#555;border:1px solid #555;">soyo女士又开启了黑脸模式，我害怕</span>
```
```css
span.text_mask {
-webkit-border-radius: 2px;
-moz-border-radius: 2px;
border-radius: 2px;
-moz-background-clip: padding;
-webkit-background-clip: padding-box;
background-clip: padding-box;
-webkit-transition: all .5s linear;
-moz-transition: all .5s linear;
-ms-transition: all .5s linear;
-o-transition: all .5s linear;
text-shadow: #555 0 0 20px
}
span.text_mask:hover {
color: #FFF !important;
text-shadow: #FFF 0 0 0px
}
```
> fix: bbcode widget appearance

- .github/ISSUE_TEMPLATE/bug.yml
- .github/workflows/pr.yaml
- lib/request/interceptor.dart
close #775 
影响使用的错误都有 GeneralWidget 可以重发请求，没有影响的也不是很需要显示 toast
用 Logger 避免被记录在日志文件里(感觉不是很需要被记录下来)
template 的修改是可以隐藏过长的 log，不然有时候要划好久（
> chore: update issue template and workflow

- lib/pages/player/player_controller.dart
- lib/request/damaku.dart
- lib/utils/string_match.dart
fix issue: #789 
目前匹配弹幕由于是通过视屏源标题来搜索dandanplay上的弹幕，在面对多季的番剧或者有BD/无修番剧时搜索不到。
采取两个方案来优化弹幕匹配
1. 通过匹配视频源标题 与 dandanplay返回的标题相似度
eg:  无职转生Ⅱ ～到了异世界就拿出真本事～ 第2部分 
之前会匹配到第一部
修改过后:
2.当视频源标题查询不到时，搜索Bangumi标题
eg: 梦想成为魔法少女(WEB无修)
> fix: 优化番剧弹幕匹配度

- lib/bean/card/bangumi_card.dart
- lib/pages/search/search_page.dart
- lib/pages/webdav_editor/webdav_editor_page.dart
- 删除了 search bar 和 search view 的阴影
- 手动实现 viewLeading 来使用 Material 3 的返回 icon (macOS 的 BackButton 一直在用错误的 icon)
- 全屏 searh view 用宽度来判断，flutter 默认是平台判断
- 隐藏 webdav 密码
- 移动了一些 padding，避免如图滚动条的出现
- clipBehavior 用 antiAlias，减少圆角锯齿
> feat: better search page appearance and obscure password

- lib/pages/webview/webview_controller.dart
- lib/pages/webview/webview_controller_impel/webview_android_controller_impel.dart
- lib/pages/webview/webview_item.dart
- lib/pages/webview/webview_item_impel/webview_android_item_impel.dart
- pubspec.lock
- pubspec.yaml
重构过程中发现以下平台差异：
1. 由于 UserScript 的 forMainFrameOnly 在 Android 上无效，脚本会注入到 iframe。beta 已支持 forMainFrameOnly，因此先将 iframeRedirectScript 移至 onLoadStart 执行。
2. Android 上 AT_DOCUMENT_END 触发时机较晚（DOM complete时），改用 AT_DOCUMENT_START。
3. 不建议使用 Android 的 ContentBlocker，目前的逻辑是会先通过 HEAD 请求获取 ContentType，再进行规则匹配。
> feat: migrate from webview_flutter to flutter_inappwebview for Android platform

- lib/pages/player/player_controller.dart
- lib/pages/player/player_item.dart
- lib/pages/webdav_editor/webdav_setting.dart
- lib/utils/webdav.dart
fix #1179  ，加强了webdav初始化验证
debug模式下每次上传都会输出
```shell
[🔔 Dio] _FileStream cannot be used to imply a default content-type, please set a proper content-type in the request.
[🔔 Dio] #0      ImplyContentTypeInterceptor.onRequest (package:dio/src/interceptors/imply_content_type.dart:33:22)
imply_content_type.dart:33
#1      DioMixin.fetch.requestInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:401:17)
dio_mixin.dart:401
#2      new Future.<anonymous closure> (dart:async/future.dart:260:40)
future.dart:260
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
timer_patch.dart:18
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:410:19)
timer_impl.dart:410
#5      _Timer._handleMessage …
```
> fix: webdav自动上传与历史记录保存冲突

- lib/app_widget.dart
- lib/pages/my/my_page.dart
- lib/pages/player/player_item.dart
- lib/pages/player/player_item_panel.dart
- lib/pages/player/smallest_player_item_panel.dart
- lib/pages/settings/danmaku/danmaku_settings.dart
- lib/pages/settings/danmaku/danmaku_settings_sheet.dart
- lib/pages/settings/danmaku/danmaku_shield_settings.dart
- lib/pages/settings/decoder_settings.dart
- lib/pages/settings/displaymode_settings.dart
- lib/pages/settings/player_settings.dart
- lib/pages/settings/super_resolution_settings.dart
- lib/pages/settings/theme_settings_page.dart
- lib/utils/constants.dart
- pubspec.lock
- pubspec.yaml
modalBottomSheet 的背景颜色和 card-settings-ui 的浅色一模一样，都是 surface container low，不过看着也还行（
有的文件只是把最大宽度的设置方式改了，maxWidth 可以让滚动条显示在最右边
设置界面的默认倍速也改成了 Slider，不知道合不合适
> feat: new settings interface with slider

- lib/pages/plugin_editor/plugin_view_page.dart
尝试了下定义一个变量来拦截返回手势，界面上出现多个 MenuAnchor 的时候会出问题，还是先把图标修复 PR 了再说
> chore: wrong plugin view page icon color

- .github/workflows/pr.yaml
- .github/workflows/release.yaml
更新 dmg 外观。由于没有签名会报错所以需要使用 `continue-on-error: true`，但是 dmg 仍然可以成功创建
| 新 | 旧 |
| --- | --- |
|<img width="660" height="422" alt="image" src="https://github.com/user-attachments/assets/067b188c-d2f5-46b0-a64d-1ebafdc3968f" />|<img width="920" height="464" alt="image" src="https://github.com/user-attachments/assets/720ab24a-b60b-47f0-9936-b134ef825928" />|
> feat: use create-dmg to generate prettier dmg
